# Generated by Django 4.0.4 on 2022-05-16 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='date_of_creation',
            new_name='created',
        ),
    ]
