# Generated by Django 4.0.4 on 2022-05-16 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_rename_date_of_creation_offer_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='date_of_bid',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='eta',
            new_name='time_of_delivery',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='date_of_creation',
        ),
    ]
