# Generated by Django 4.0.4 on 2022-05-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_offer_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='reviewed_by_bidder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='reviewed_by_host',
            field=models.BooleanField(default=False),
        ),
    ]
