# Generated by Django 4.0.4 on 2022-05-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_offer_reviewed_by_bidder_offer_reviewed_by_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
