# Generated by Django 4.0.4 on 2022-05-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0007_alter_offer_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/offer/'),
        ),
    ]
