# Generated by Django 4.0.4 on 2022-05-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0009_offer_address_offer_latitude_offer_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='distance_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Distance_text'),
        ),
        migrations.AddField(
            model_name='offer',
            name='distance_value',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Distance_value'),
        ),
    ]
