# Generated by Django 4.0.4 on 2022-05-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0010_offer_distance_text_offer_distance_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bid',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
