# Generated by Django 4.0.4 on 2022-05-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_dark_mode',
            field=models.BooleanField(default=True),
        ),
    ]
