# Generated by Django 4.0.4 on 2022-05-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_avatar_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='static/users/images/avatar.svg', null=True, upload_to='static/users/images'),
        ),
    ]
