# Generated by Django 4.0.4 on 2022-05-25 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_address_user_have_address_user_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='have_address',
            new_name='changed_address',
        ),
    ]
