# Generated by Django 4.0.4 on 2022-05-31 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_have_address_user_changed_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy_rating', models.FloatField(blank=True, default=0)),
                ('quality_rating', models.FloatField(blank=True, default=0)),
                ('arrival_rating', models.FloatField(blank=True, default=0)),
                ('cost_rating', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='delivery_rating',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.rating'),
        ),
    ]
