# Generated by Django 4.0.4 on 2022-05-31 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rating_alter_user_delivery_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='delivery_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.rating'),
        ),
    ]
