# Generated by Django 4.0.4 on 2022-06-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_delivery_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='avg',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
