# Generated by Django 4.0.4 on 2022-04-23 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bid_request_request_host_request_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='request',
            new_name='transaction',
        ),
        migrations.AddField(
            model_name='request',
            name='final_bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bid'),
        ),
    ]
