# Generated by Django 4.0.4 on 2022-04-23 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_request_bid_transaction_request_final_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='final_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bid'),
        ),
    ]
